name: Set-up LDC to target macOS ARM64
description: Adds a working arm64-apple-macos target to LDC.

runs:
  using: composite
  steps:
    - name: Install Clang
      shell: bash
      run: sudo apt-get install -y clang lld

    - name: Set-up macOS cross-compilation
      shell: bash
      run: |
        mkdir -p $HOME/.ldc/
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
        # Use macOS 14.0 SDK (newer, compatible with Tahoe 26.2)
        curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/14.4/MacOSX14.4.sdk.tar.xz || \
        curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/14.0/MacOSX14.0.sdk.tar.xz || \
        curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz
        # Extract the SDK (handle different naming)
        if [ -f MacOSX14.4.sdk.tar.xz ]; then
          tar -xf ./MacOSX14.4.sdk.tar.xz -C $HOME
          SDK_PATH="$HOME/MacOSX14.4.sdk"
        elif [ -f MacOSX14.0.sdk.tar.xz ]; then
          tar -xf ./MacOSX14.0.sdk.tar.xz -C $HOME
          SDK_PATH="$HOME/MacOSX14.0.sdk"
        elif [ -f MacOSX13.3.sdk.tar.xz ]; then
          tar -xf ./MacOSX13.3.sdk.tar.xz -C $HOME
          SDK_PATH="$HOME/MacOSX13.3.sdk"
        else
          echo "Failed to download SDK, falling back to 11.0"
          curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.0.sdk.tar.xz
          tar -xf ./MacOSX11.0.sdk.tar.xz -C $HOME
          SDK_PATH="$HOME/MacOSX11.0.sdk"
        fi
        cp $(dirname $(which ldc2))/../etc/ldc2.conf $HOME/.ldc/ldc2.conf
        cat << EOF | tee $HOME/.ldc/ldc2.conf
        "arm64-apple-macos":
        {
            // default switches injected before all explicit command-line switches
            switches = [
                "-gcc=clang",
                "-linker=lld-15",
                "-Xcc=-target",
                "-Xcc=arm64-apple-macos",
                "-Xcc=-isysroot",
                "-Xcc=$SDK_PATH",
                "-Xcc=-F",
                "-Xcc=$HOME/ldc2-$LDC_VERSION-osx-arm64/lib",
                "-Xcc=-mmacosx-version-min=14.0",
                "-L=-platform_version",
                "-L=macos",
                "-L=14.0.0",
                "-L=0.0.0",
                "-defaultlib=phobos2-ldc,druntime-ldc",
            ];
            // default switches appended after all explicit command-line switches
            post-switches = [
                "-I$HOME/ldc2-$LDC_VERSION-osx-arm64/import",
            ];
            // default directories to be searched for libraries when linking
            lib-dirs = [
                "$HOME/ldc2-$LDC_VERSION-osx-arm64/lib",
            ];
        };
        EOF
        mkdir $HOME/ldc-macos
        curl -LO https://github.com/ldc-developers/ldc/releases/download/v$LDC_VERSION/ldc2-$LDC_VERSION-osx-arm64.tar.xz
        tar -xf ./ldc2-$LDC_VERSION-osx-arm64.tar.xz -C $HOME
